Repository recipe-hub/recipehub-api, pull requests merged in 2020-10, with the labels that each got.

#1 Feature/models
  go.mod
  go.sum
  main.go
  models/categories.go
  models/ingredients.go
  models/recipes.go
  models/setup.go
Labels: api, models

#2 Feature/users model
  .editorconfig
  .env.template
  .gitignore
  go.mod
  go.sum
  main.go
  models/recipes.go
  models/setup.go
  models/users.go
  routes/setup.go
  utils/env.go
Labels: api, models

#3 ingredients controller
  controllers/ingredients.go
Labels: api, hacktoberfest-accepted

#4 Create Ingredients Routes
  routes/ingredients.go
  routes/setup.go
Labels: api, hacktoberfest-accepted

#6 Create Categories Routes
  routes/categories.go
Labels: api, hacktoberfest-accepted

#7 Users Controllers
  controllers/users.go
  models/users.go
Labels: api, hacktoberfest-accepted

#8 create hash password function
  controllers/users.go
  go.mod
  go.sum
  utils/security.go
Labels: api, hacktoberfest-accepted

#9 fix var name on categories routes
  routes/categories.go
  routes/setup.go
Labels: api, hacktoberfest-accepted

#12 Fix http method of the update ingredients endpoint
  routes/ingredients.go
Labels: api, hacktoberfest-accepted

#13 Create LICENSE
  LICENSE
Labels: api, hacktoberfest-accepted

#14 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: api, hacktoberfest-accepted

#15 Create README.md
  README.md
Labels: api, hacktoberfest-accepted

#16 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: api
